export const TutorCustomer = [
  {
    id: 1,
    name: "Wajahat Zahoor",
    location: "Islamabad",
    university: "Riphah International University Islamabad",
    degree: "MSc Physics",
    experience: "5 Years",
    rating: 4,
    bio: "Experienced physics tutor with passion for teaching and student success.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_6027.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 2,
    name: "Ali Raza",
    location: "Lahore",
    university: "Punjab University",
    degree: "MSc Mathematics",
    experience: "6 Years",
    rating: 5,
    bio: "Expert in mathematics with strong problem-solving techniques.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5971.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 3,
    name: "Ayesha Khan",
    location: "Karachi",
    university: "University of Karachi",
    degree: "MSc Chemistry",
    experience: "4 Years",
    rating: 4,
    bio: "Dedicated chemistry tutor focusing on conceptual learning.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5975.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 4,
    name: "Usman Tariq",
    location: "Rawalpindi",
    university: "COMSATS University",
    degree: "BS Computer Science",
    experience: "5 Years",
    rating: 5,
    bio: "Programming tutor specializing in web and software development.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5964.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 5,
    name: "Sara Ahmed",
    location: "Islamabad",
    university: "NUST",
    degree: "MS English",
    experience: "7 Years",
    rating: 4,
    bio: "English language and literature tutor with modern teaching methods.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5954.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 6,
    name: "Hamza Iqbal",
    location: "Faisalabad",
    university: "GC University Faisalabad",
    degree: "MSc Physics",
    experience: "3 Years",
    rating: 4,
    bio: "Physics tutor focused on board exam preparation.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5937.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 7,
    name: "Fatima Noor",
    location: "Multan",
    university: "BZU Multan",
    degree: "MSc Biology",
    experience: "5 Years",
    rating: 5,
    bio: "Biology tutor with strong focus on medical entrance exams.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5941.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 8,
    name: "Bilal Hussain",
    location: "Peshawar",
    university: "University of Peshawar",
    degree: "MSc Statistics",
    experience: "4 Years",
    rating: 4,
    bio: "Statistics tutor making complex data concepts simple.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5932.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 9,
    name: "Zain Malik",
    location: "Sialkot",
    university: "UET Lahore",
    degree: "BS Electrical Engineering",
    experience: "6 Years",
    rating: 5,
    bio: "Engineering tutor with practical industry experience.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5929.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 10,
    name: "Hira Siddique",
    location: "Gujranwala",
    university: "University of Gujrat",
    degree: "MSc Economics",
    experience: "5 Years",
    rating: 4,
    bio: "Economics tutor with analytical and real-world examples.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5845.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },

  {
    id: 11,
    name: "Ahmed Khan",
    location: "Islamabad",
    university: "FAST NUCES",
    degree: "BS Software Engineering",
    experience: "4 Years",
    rating: 5,
    bio: "Frontend & backend development tutor.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5828.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 12,
    name: "Noor Fatima",
    location: "Lahore",
    university: "LUMS",
    degree: "MS Psychology",
    experience: "6 Years",
    rating: 4,
    bio: "Psychology tutor with student-centered teaching approach.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5815.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 13,
    name: "Saad Ali",
    location: "Karachi",
    university: "NED University",
    degree: "BE Mechanical",
    experience: "7 Years",
    rating: 5,
    bio: "Mechanical engineering tutor with hands-on teaching.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5827.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 14,
    name: "Maryam Asif",
    location: "Islamabad",
    university: "IIUI",
    degree: "MSc Islamic Studies",
    experience: "5 Years",
    rating: 4,
    bio: "Islamic studies tutor with modern teaching style.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5697.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 15,
    name: "Hassan Rauf",
    location: "Lahore",
    university: "UET Lahore",
    degree: "BS Civil Engineering",
    experience: "6 Years",
    rating: 5,
    bio: "Civil engineering tutor focused on core concepts.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5656.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 16,
    name: "Sana Malik",
    location: "Karachi",
    university: "IBA Karachi",
    degree: "BBA",
    experience: "4 Years",
    rating: 4,
    bio: "Business studies tutor with practical examples.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5586.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 17,
    name: "Farhan Ahmed",
    location: "Hyderabad",
    university: "University of Sindh",
    degree: "MSc IT",
    experience: "5 Years",
    rating: 4,
    bio: "IT tutor specializing in databases and networking.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5588.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 18,
    name: "Rabia Noor",
    location: "Quetta",
    university: "University of Balochistan",
    degree: "MSc Zoology",
    experience: "6 Years",
    rating: 4,
    bio: "Zoology tutor with research-based teaching.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5574.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 19,
    name: "Imran Shah",
    location: "Abbottabad",
    university: "COMSATS Abbottabad",
    degree: "BS AI",
    experience: "3 Years",
    rating: 5,
    bio: "AI & machine learning tutor for beginners.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5562.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
  {
    id: 20,
    name: "Khadija Ali",
    location: "Bahawalpur",
    university: "Islamia University Bahawalpur",
    degree: "MSc Education",
    experience: "8 Years",
    rating: 5,
    bio: "Professional educator with strong mentoring skills.",
    image: "https://foriedu.com/uploads/profile-images/user_dp_5506.jpg",
    contact: {
      whatsapp: true,
      message: true,
    },
  },
];
